version: '3'

services:
  dreambooth:
    image: saladtechnologies/dreambooth:base
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # - ./images:/images
      - ./output:/output
      - ./models:/models
    environment:
      - HF_HOME=/models
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_ENDPOINT_URL
      - CHECKPOINT_BUCKET_NAME=training-checkpoints
      - CHECKPOINT_BUCKET_PREFIX=loras/timber/
      - DATA_BUCKET_NAME=training-data
      - DATA_BUCKET_PREFIX=timber/
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
          