version: '3'

services:
  autotrain:
    image: saladtechnologies/autotrain:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./images:/images
      - ./output:/output
      - ./models:/models
    environment:
      - HF_HOME=/models
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_ENDPOINT_URL
      - BUCKET_NAME=training-checkpoints
      - BUCKET_PREFIX=loras/timber/
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
          