version: '3'

services:
  dreambooth:
    image: saladtechnologies/dreambooth:sdxl
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
    environment:
      - PROMPT=a photo of timberdog
      - LEARNING_RATE=2e-6
      - MAX_TRAIN_STEPS=500
      - TRAIN_BATCH_SIZE=1
      - USE_8BIT_ADAM=false
      - MIXED_PRECISION=fp16
      - RESOLUTION=1024
      - GRADIENT_ACCUMULATION_STEPS=4
      - LR_SCHEDULER=constant
      - LR_WARMUM_STEPS=0
      - TRAIN_TEXT_ENCODER=false
      - GRADIENT_CHECKPOINTING=false
      - MODEL_NAME=stabilityai/stable-diffusion-xl-base-1.0
      - VAE_PATH=madebyollin/sdxl-vae-fp16-fix
      - TRAINING_SCRIPT=train_dreambooth_lora_sdxl.py
      - CHECKPOINTING_STEPS=20
      - VALIDATION_PROMPT=a photo of timberdog playing in the snow
      - VALIDATION_EPOCHS=10
      
      - CHECKPOINT_BUCKET_NAME=training-checkpoints
      - CHECKPOINT_BUCKET_PREFIX=loras/timber4/
      - DATA_BUCKET_NAME=training-data
      - DATA_BUCKET_PREFIX=timber/
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_ENDPOINT_URL

      - REPORT_TO=wandb
      - WANDB_API_KEY

      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile.sdxl
    # command: nvidia-smi
    # volumes:
    #   - ./images:/images
    #   - ./output:/output
    #   - ./models:/models
    
          