FROM saladtechnologies/dreambooth:base

COPY models /models

ENV MODEL_NAME "stabilityai/stable-diffusion-xl-base-1.0"
ENV VAE_PATH "madebyollin/sdxl-vae-fp16-fix"
ENV DREAMBOOTH_SCRIPT "train_dreambooth_lora_sdxl.py"
ENV RESOLUTION "1024"